export const CHISME_POSTED = 'CHISME_POSTED';  
export const CHISME_DELETED = 'CHISME_DELETED';
export const CHISME_UPDATED = 'CHISME_UPDATED';
export const CHISME_REQUEST = 'CHISME_REQUEST';
export const CHISME_SUCCESS = 'CHISME_SUCCESS';
export const CHISME_CHANGED = 'CHISME_CHANGED';